"""fix column name

Revision ID: 31e2c8f70754
Revises: 77d7451ecd1d
Create Date: 2025-12-15 18:52:58.099769

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "31e2c8f70754"
down_revision: Union[str, Sequence[str], None] = "77d7451ecd1d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("alerts", sa.Column("is_triggered", sa.Boolean(), nullable=True))
    op.drop_column("alerts", "is_tiggered")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "alerts",
        sa.Column("is_tiggered", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.drop_column("alerts", "is_triggered")
    # ### end Alembic commands ###
