"""Create tables

Revision ID: 3472df1d1e2b
Revises: 
Create Date: 2025-12-14 15:23:45.672537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3472df1d1e2b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cryptocurrency',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('coingecko_id', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('symbol')
    )
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('cryptocurrency_id', sa.UUID(), nullable=False),
    sa.Column('threshold_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cryptocurrency_id'], ['cryptocurrency.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('cryptocurrency_price',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cryptocurrency_id', sa.UUID(), nullable=False),
    sa.Column('price_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('market_cap_usd', sa.Numeric(precision=30, scale=2), nullable=True),
    sa.Column('total_volume_24h_usd', sa.Numeric(precision=30, scale=2), nullable=True),
    sa.Column('high_24h', sa.Numeric(precision=30, scale=2), nullable=True),
    sa.Column('low_24h', sa.Numeric(precision=30, scale=2), nullable=True),
    sa.Column('price_change_24h', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('price_change_percentage_24h', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['cryptocurrency_id'], ['cryptocurrency.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cryptocurrency_price')
    op.drop_table('alerts')
    op.drop_table('cryptocurrency')
    # ### end Alembic commands ###
