"""add is_triggered column

Revision ID: 77d7451ecd1d
Revises: 3472df1d1e2b
Create Date: 2025-12-15 18:30:33.384644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77d7451ecd1d'
down_revision: Union[str, Sequence[str], None] = '3472df1d1e2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('is_tiggered', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'alerts', ['id'])
    op.create_unique_constraint(None, 'cryptocurrency', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cryptocurrency', type_='unique')
    op.drop_constraint(None, 'alerts', type_='unique')
    op.drop_column('alerts', 'is_tiggered')
    # ### end Alembic commands ###
