"""add telegram_id to alerts

Revision ID: add_telegram_id_to_alerts
Revises: 31e2c8f70754
Create Date: 2025-12-18 12:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "add_telegram_id_to_alerts"
down_revision: Union[str, Sequence[str], None] = "31e2c8f70754"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("alerts", sa.Column("telegram_id", sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("alerts", "telegram_id")
    # ### end Alembic commands ###
