"""empty message

Revision ID: 0703d2d7bdd3
Revises: 
Create Date: 2025-12-27 14:43:45.050966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0703d2d7bdd3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('wallet_address', sa.String(length=50), nullable=False),
    sa.Column('last_active', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid'),
    sa.UniqueConstraint('wallet_address')
    )
    op.create_table('nonce',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('wallet_address', sa.String(length=50), nullable=False),
    sa.Column('nonce', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('statement', sa.String(), nullable=True),
    sa.Column('uri', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('expiration_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('chain_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['wallet_address'], ['wallet.wallet_address'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nonce')
    op.drop_table('wallet')
    # ### end Alembic commands ###
