"""add hashed refresh & is revoked

Revision ID: 07edc9d8ae5b
Revises: 0703d2d7bdd3
Create Date: 2025-12-30 19:07:48.194376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '07edc9d8ae5b'
down_revision: Union[str, Sequence[str], None] = '0703d2d7bdd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alerts')
    op.drop_table('user_preferences')
    op.drop_table('alembic_version_notification_service')
    op.drop_table('cryptocurrency_price')
    op.drop_table('notifications')
    op.drop_table('cryptocurrency')
    op.drop_table('alembic_version')
    op.create_unique_constraint(None, 'nonce', ['uuid'])
    
    # Add columns as nullable first
    op.add_column('wallet', sa.Column('hashed_refresh_token', sa.String(), nullable=True))
    op.add_column('wallet', sa.Column('is_revoked', sa.Boolean(), nullable=True, server_default='false'))
    
    # Set default value for existing rows
    op.execute("UPDATE wallet SET hashed_refresh_token = '' WHERE hashed_refresh_token IS NULL")
    op.execute("UPDATE wallet SET is_revoked = false WHERE is_revoked IS NULL")
    
    # Now make hashed_refresh_token NOT NULL
    op.alter_column('wallet', 'hashed_refresh_token', nullable=False)
    
    op.create_unique_constraint(None, 'wallet', ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wallet', type_='unique')
    op.drop_column('wallet', 'is_revoked')
    op.drop_column('wallet', 'hashed_refresh_token')
    op.drop_constraint(None, 'nonce', type_='unique')
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc'))
    )
    op.create_table('cryptocurrency',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('coingecko_id', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='cryptocurrency_pkey'),
    sa.UniqueConstraint('id', name='cryptocurrency_id_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('name', name='cryptocurrency_name_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('symbol', name='cryptocurrency_symbol_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('channel', postgresql.ENUM('TELEGRAM', 'EMAIL', name='channelenum'), autoincrement=False, nullable=False),
    sa.Column('idempotency_key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('message', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('recipient', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('SENT', 'PENDING', 'FAILED', name='statusenum'), autoincrement=False, nullable=False),
    sa.Column('sent_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('notifications_pkey')),
    sa.UniqueConstraint('idempotency_key', name=op.f('notifications_idempotency_key_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('cryptocurrency_price',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('cryptocurrency_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('price_usd', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('last_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('market_cap_usd', sa.NUMERIC(precision=30, scale=2), autoincrement=False, nullable=True),
    sa.Column('total_volume_24h_usd', sa.NUMERIC(precision=30, scale=2), autoincrement=False, nullable=True),
    sa.Column('high_24h', sa.NUMERIC(precision=30, scale=2), autoincrement=False, nullable=True),
    sa.Column('low_24h', sa.NUMERIC(precision=30, scale=2), autoincrement=False, nullable=True),
    sa.Column('price_change_24h', sa.NUMERIC(precision=20, scale=8), autoincrement=False, nullable=True),
    sa.Column('price_change_percentage_24h', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cryptocurrency_id'], ['cryptocurrency.id'], name=op.f('cryptocurrency_price_cryptocurrency_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('cryptocurrency_price_pkey'))
    )
    op.create_table('alembic_version_notification_service',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_notification_service_pkc'))
    )
    op.create_table('user_preferences',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('email_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('telegram_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('telegram_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('user_preferences_pkey')),
    sa.UniqueConstraint('email', name=op.f('user_preferences_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('telegram_id', name=op.f('user_preferences_telegram_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('cryptocurrency_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('threshold_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_triggered', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('telegram_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cryptocurrency_id'], ['cryptocurrency.id'], name=op.f('alerts_cryptocurrency_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('alerts_pkey')),
    sa.UniqueConstraint('id', name=op.f('alerts_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
