"""add hashed refresh & is revoked

Revision ID: 07edc9d8ae5b
Revises: 0703d2d7bdd3
Create Date: 2025-12-30 19:07:48.194376

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "07edc9d8ae5b"
down_revision: Union[str, Sequence[str], None] = "0703d2d7bdd3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "nonce", ["uuid"])

    # Add columns as nullable first
    op.add_column(
        "wallet", sa.Column("hashed_refresh_token", sa.String(), nullable=True)
    )
    op.add_column(
        "wallet",
        sa.Column("is_revoked", sa.Boolean(), nullable=True, server_default="false"),
    )

    # Set default value for existing rows
    op.execute(
        "UPDATE wallet SET hashed_refresh_token = '' WHERE hashed_refresh_token IS NULL"
    )
    op.execute("UPDATE wallet SET is_revoked = false WHERE is_revoked IS NULL")

    # Now make hashed_refresh_token NOT NULL
    op.alter_column("wallet", "hashed_refresh_token", nullable=False)

    op.create_unique_constraint(None, "wallet", ["uuid"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "wallet", type_="unique")
    op.drop_column("wallet", "is_revoked")
    op.drop_column("wallet", "hashed_refresh_token")
    op.drop_constraint(None, "nonce", type_="unique")
    # ### end Alembic commands ###
